In [54]:
import pandas as pd

In [55]:
df = pd.read_csv('titanic.csv')

In [56]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [57]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [58]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [59]:
df["Age"].fillna(df["Age"].median(), inplace=True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_21308\2097741607.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)

In [60]:
df.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   29.599282    0.447368    0.392344   35.627188
std     120.810458    0.841838   12.703770    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   23.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   35.750000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [61]:
df.drop(columns=["Cabin", "Ticket", "Name"], inplace=True)

In [62]:
df.dtypes

PassengerId      int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked        object
dtype: object

In [63]:
df["Age"] = df["Age"].astype(int)

In [64]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

In [65]:
df.head()

   PassengerId  Pclass  Sex  Age  SibSp  Parch     Fare Embarked
0          892       3    0   34      0      0   7.8292        Q
1          893       3    1   47      1      0   7.0000        S
2          894       2    0   62      0      0   9.6875        Q
3          895       3    0   27      0      0   8.6625        S
4          896       3    1   22      1      1  12.2875        S

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
df[['Age']] = scaler.fit_transform(df[['Age']])
df.head()

   PassengerId  Pclass  Sex       Age  SibSp  Parch     Fare Embarked
0          892       3    0  0.447368      0      0   7.8292        Q
1          893       3    1  0.618421      1      0   7.0000        S
2          894       2    0  0.815789      0      0   9.6875        Q
3          895       3    0  0.355263      0      0   8.6625        S
4          896       3    1  0.289474      1      1  12.2875        S

In [68]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Fare']] = scaler.fit_transform(df[['Fare']])
df.head()

   PassengerId  Pclass  Sex       Age  SibSp  Parch      Fare Embarked
0          892       3    0  0.447368      0      0 -0.497811        Q
1          893       3    1  0.618421      1      0 -0.512660        S
2          894       2    0  0.815789      0      0 -0.464532        Q
3          895       3    0  0.355263      0      0 -0.482888        S
4          896       3    1  0.289474      1      1 -0.417971        S

In [69]:
df.to_csv('cleaned_titanic.csv', index=False)